"""addedimageurlandname

Revision ID: 339f2728452d
Revises: dda24ac8ca9d
Create Date: 2017-07-10 18:12:59.108000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339f2728452d'
down_revision = 'dda24ac8ca9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('image_filename', sa.String(), nullable=True))
    op.add_column('wishes', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishes', 'image_url')
    op.drop_column('wishes', 'image_filename')
    # ### end Alembic commands ###
