"""addedwish_status

Revision ID: 76a60f58e11d
Revises: d239686fdbb9
Create Date: 2017-07-10 15:49:30.565000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a60f58e11d'
down_revision = 'd239686fdbb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('wish_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishes', 'wish_status')
    # ### end Alembic commands ###
